### ISSUE TITLE
tint2 panel is not configurable 

### ISSUE THREAD

**Issue by karthick-kk** [leomarcov/debian-openbox#2]
Tried to change the taskbar alignment from horizontal to vertical using the tint2 gui customizer. When selecting any theme from the panel it does not change and always fallback to the default one.

**Comment by leomarcov** [comment]
Hi, thanks for your aportation. I have solve the problem (i think). Now when open tint2 gui customizer appers menu.tint2rc (upper menu in desktop) and taskbar.tint2rc and you can customize them.
